[project]
authors = ["Jason Mercer <jasonjmercer@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "py4ds"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.3.5,<5"
pytorch = ">=2.5.1,<3"
